[ENH] OWSetEnrichment: use filter proxy model
biolab/orange-bio pull request #119
Opened 2017-11-14 08:29 UTC by JakaKokosar

- Re-enable string search and move filtering into a filter proxy model. 
- Remove UserWarning messages by using Error and Warning class.

2017-11-14 08:29 UTC, JakaKokosar commented
@markotoplak

2018-01-11 13:30 UTC, ales-erjavec requested changes

2018-01-11 13:30 UTC, ales-erjavec commented on orangecontrib/bio/widgets3/OWSetEnrichment.py
> +from Orange.widgets.utils.messages import UnboundMsg
You can use `from Orange.widgets import Msg` and remove the reassign below.

2018-01-11 13:30 UTC, ales-erjavec commented on orangecontrib/bio/widgets3/OWSetEnrichment.py
> +            self.Error.no_data_onInput()
Don't show an error here.

2018-01-11 13:30 UTC, ales-erjavec commented on orangecontrib/bio/widgets3/OWSetEnrichment.py
> +        model = self.source_model
This model is only appended to. Running multiple enrichement tasks one after the other results in multiplied rows in the model and view:
<img width="557" alt="screen shot 2018-01-11 at 14 20 15" src="https://user-images.githubusercontent.com/4716745/34827483-997e7abc-f6da-11e7-92c3-99f0b34623b1.png">

2018-02-02 11:23 UTC, ales-erjavec commented
Closed in favor of gh-122

2018-02-02 11:23 UTC, closed without merging